name: CI
on:
  push:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@56b893ae09c48f21c16a9793a107c2723ccc123a # v13
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # v6.4.9
      - run: sbt -v lint
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  test:
    strategy:
      fail-fast: false
      matrix:
        jdk: [ adopt@1.8, adopt@1.11, adopt@1.14 ]
        scala: [ 3.0.1, 2.13.5, 2.12.13 ]
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@56b893ae09c48f21c16a9793a107c2723ccc123a # v13
        with:
          java-version: ${{ matrix.jdk }}
      - uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # v6.4.9
      - uses: olafurpg/setup-gpg@a62c5903e98d692e520bc2f46103b919a61dd386 # v3
      - name: sbt test
        run: sbt -v ++${{ matrix.scala }} test
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && ${{ !github.event.repository.fork }}
    needs: test
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@2e9644b0b86a2c052525921f181f905dc8102da5 # v0.15.3
        env:
          GITHUB_TOKEN: "${{ secrets.CW_SCALA_STEWARD_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_FILTER_AUTHOR: "cw-scala-steward"
